services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports: ["2181:2181"]

  kafka:
    image: confluentinc/cp-kafka:7.6.0
    depends_on: [zookeeper]
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports: ["9093:9093"]

  minio:
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    ports: ["9000:9000","9001:9001"]
    volumes: ["./lake:/data"]

  postgres:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: retail
    ports: ["5432:5432"]
    volumes: ["./data/seeds:/docker-entrypoint-initdb.d"]

  airflow:
    image: apache/airflow:2.9.1
    depends_on: [postgres]
    environment:
      AIRFLOW__CORE__LOAD_EXAMPLES: "False"
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://postgres:postgres@postgres:5432/retail
    volumes:
      - ./infra/airflow/dags:/opt/airflow/dags
    command: >
      bash -c "
      airflow db init &&
      airflow users create --username admin --password admin --firstname a --lastname a --role Admin --email a@a.a;
      airflow webserver & airflow scheduler"
    ports: ["8080:8080"]

  spark:
    image: bitnami/spark:3.5
    environment:
      SPARK_MODE: master
    ports: ["7077:7077","8081:8080"]
    volumes:
      - ./spark_jobs:/opt/spark_jobs
      - ./lake:/lake